package protocol

import "encoding/json"

// Outcome values accepted by Cloud (OpenAPI SessionReport.outcome).
const (
	OutcomeCompleted = "completed"
	OutcomeFailed    = "failed"
	OutcomeAborted   = "aborted"
)

// HeaderIdempotency carries ReportID on the report endpoints. Cloud rejects a
// request whose header and body disagree, so the two are never set separately.
const HeaderIdempotency = "Idempotency-Key"

// SessionReport is what Edge sends when a broadcast ends: one immutable record of
// how the session actually went, assembled from observations already collected for
// the operator panel.
//
// Two endpoints take it, and the difference is only where the session binding comes
// from — the body is identical:
//
//	POST /edge/v1/sessions/{sessionId}/report   the broadcast had a Cloud session
//	POST /edge/v1/reports                       it did not (the normal field case today)
//
// The session id is therefore NOT a body field. It is the path, and Cloud stores it
// as a nullable relation.
type SessionReport struct {
	// ReportID identifies ONE completed report and is what Idempotency-Key carries.
	//
	// Not the session id, and the distinction is load-bearing: Edge writes a report
	// when the LAST camera leaves, and a rejoin starts a fresh internal session, so
	// one Cloud production session legitimately produces several reports — a router
	// blip, a roam between access points, a pause between takes, a battery swap.
	// Keying idempotency on the session id would have kept the first of those and
	// silently dropped the rest, and the first is often a short fragment from just
	// before everything dropped. Measured on the bench: 25 stored reports, one
	// session id, 12 s to 1591 s.
	//
	// Generated by Edge, once, and carried on disk, so a resend after a restart
	// repeats the same key instead of creating a duplicate record.
	ReportID string `json:"report_id"`

	DurationSec int    `json:"duration_sec"`
	Outcome     string `json:"outcome"`

	// PlayoutDelayMs is the deadline the held rates below were measured against, and
	// without it they cannot be read at all: 10% held at 240 ms and 10% at 400 ms
	// describe two different handsets and two different diagnoses. Kept out of
	// CameraReport because the buffer is one for the whole session, set by the worst
	// camera.
	//
	// A pointer, because "an Edge too old to report it" and "reported as zero" are
	// different facts and Cloud keeps the column nullable to say so. A plain int would
	// make every old report claim the session ran at a zero-millisecond buffer.
	PlayoutDelayMs *int `json:"playout_delay_ms,omitempty"`

	// ConfigSnapshot and CapabilitySnapshot are carried, not interpreted. Their shape
	// belongs to the Edge that produced them — Edge builds the config snapshot from its
	// own sessioncfg, which is not this module's — so the wire type is raw JSON and both
	// sides move the bytes unchanged.
	//
	// They were typed structs in v0.2.0, and that was a mistake with a measured cost:
	// decoding into a typed struct and re-encoding to store it invented fields the Edge
	// never sent (an "operational" block asserting playout_delay_ms: 0 in a record whose
	// whole purpose is to say what the delay was) and silently dropped fields this module
	// did not know yet. A report is an immutable record of one broadcast; normalising it
	// through whichever contract version the reader happens to run makes it evidence of
	// the reader, not of the broadcast.
	ConfigSnapshot     json.RawMessage `json:"config_snapshot,omitempty"`
	CapabilitySnapshot json.RawMessage `json:"capability_snapshot,omitempty"`
	Cameras            []CameraReport  `json:"cameras"`
	Warnings           []string        `json:"warnings,omitempty"`
}

// CameraReport is one camera's share of the session.
type CameraReport struct {
	DeviceKey string `json:"device_key"`
	SlotIndex int    `json:"slot_index"`
	// StreamingSec is time actually delivering frames, which is NOT the session
	// duration: a camera that joined late or dropped out has less.
	StreamingSec   int     `json:"streaming_sec"`
	Reconnects     int     `json:"reconnects"`
	HeldFramesPct  float64 `json:"held_frames_pct"`
	SyncErrorMsP95 float64 `json:"sync_error_ms_p95"`
	// CauseHistogram is the SHARE of observed windows attributed to each held cause
	// (none/late/starved/resync). Shares, not counts, so reports of different lengths
	// stay comparable — the useful question is "what fraction of the session was
	// starved", never "how many one-second windows were".
	//
	// Values within one camera sum to 1. Aggregating across cameras therefore means
	// averaging, not adding: a sum over four cameras reaches 4 and stops being a share.
	CauseHistogram map[string]float64 `json:"cause_histogram,omitempty"`
}
